webtalk_init -webtalk_dir C:/Xilinx/526_FinalProject/526_RobotArm_Main/526_RobotArm_Main.sim/sim_1/behav/xsim/xsim.dir/tb_top_level_controller_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May  5 01:42:58 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212015417_0_0_144" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4e908eca-3c5c-4154-9832-44eef735e032" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3a79f31a38874e21af030ff93b0e8b20" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3700X 8-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3593 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6416_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1703902258 -regid "212015417_0_0_144" -xml C:/Xilinx/526_FinalProject/526_RobotArm_Main/526_RobotArm_Main.sim/sim_1/behav/xsim/xsim.dir/tb_top_level_controller_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Xilinx/526_FinalProject/526_RobotArm_Main/526_RobotArm_Main.sim/sim_1/behav/xsim/xsim.dir/tb_top_level_controller_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Xilinx/526_FinalProject/526_RobotArm_Main/526_RobotArm_Main.sim/sim_1/behav/xsim/xsim.dir/tb_top_level_controller_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
